# Generated by Django 4.2.2 on 2023-07-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirts",
            name="shop_image",
            field=models.CharField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="shirts",
            name="shop_name",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
