# Generated by Django 4.2.2 on 2023-07-04 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0002_shirts_shop_image_shirts_shop_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shirts",
        ),
    ]
