# Generated by Django 4.2.2 on 2023-07-08 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shirts",
        ),
    ]
