# Generated by Django 4.2.2 on 2023-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0007_cartmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="product_image",
            field=models.CharField(max_length=10000),
        ),
    ]
