# Generated by Django 4.2.2 on 2023-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0008_alter_cartmodel_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="shop_image",
            field=models.CharField(max_length=10000),
        ),
    ]
