# Generated by Django 4.2.2 on 2023-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0009_alter_cartmodel_shop_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="shop_image",
            field=models.CharField(max_length=100000),
        ),
    ]
