# Generated by Django 4.2.2 on 2023-07-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0010_alter_cartmodel_shop_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shopname", models.CharField(max_length=50)),
                ("shopimage", models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name="Shopproducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.CharField(max_length=10000)),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.IntegerField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_1.shop"
                    ),
                ),
            ],
        ),
    ]
