# Generated by Django 4.2.2 on 2023-07-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0011_shop_shopproducts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproducts",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="app_1.shop",
            ),
        ),
    ]
