# Generated by Django 4.2.2 on 2023-07-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0012_alter_shopproducts_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cartproductname", models.CharField(max_length=300)),
                ("Cartproductimage", models.CharField(max_length=100000)),
                ("Cartproductprice", models.IntegerField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartshopchildren",
                        to="app_1.shop",
                    ),
                ),
            ],
        ),
    ]
