# Generated by Django 4.2.4 on 2023-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0013_cartshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartshop",
            name="username",
            field=models.CharField(default="None", max_length=300),
        ),
    ]
