# Generated by Django 4.2.4 on 2023-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0014_cartshop_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("productname", models.CharField(max_length=5000)),
                ("productimage", models.CharField(max_length=100000)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartproducts",
                        to="app_1.shop",
                    ),
                ),
            ],
        ),
    ]
